version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: studentdb
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data/

volumes:
  postgres_volume: 
